---
name: Build & Test
description: Build and test a Docker image, loading the result into Docker.
inputs:
  image:
    description: The name of the image to build
    required: true
  platform:
    description: Platform to build for
    required: false
    default: linux/amd64
  build-args:
    description: Extra build arguments to pass to the image
    required: false
    default: ""
outputs:
  imageid:
    description: Image ID
    value: ${{ steps.build.outputs.image-id }}
  digest:
    description: Image digest
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: Build result metadata
    value: ${{ steps.build.outputs.metadata }}
  image:
    description: Image name
    value: ${{ inputs.image }}:buildcache

runs:
  using: "composite"
  steps:
    # https://github.com/docker/build-push-action
    - name: Build
      id: build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ inputs.image }}
        build-args: |
          REGISTRY=localhost:5000
          OWNER=${{ github.repository_owner }}
          ${{ inputs.build-args }}
        tags: localhost:5000/${{ github.repository_owner }}/${{ inputs.image }}:buildcache
        platforms: ${{ inputs.platforms }}

    - name: Test
      shell: bash
      run: |
        docker run --rm \
        --mount=type=bind,source="./tests/${{ inputs.image }}.sh",target=/tmp/test.sh \
        localhost:5000/${{ github.repository_owner }}/${{ inputs.image }}:buildcache \
        bash /tmp/test.sh
