[workspace]
authors = ["Adam Blake <adam@ablake.dev>"]
channels = ["conda-forge", "default"]
description = "CourseKata Jupyter environments"
name = "coursekata"
platforms = ["linux-aarch64", "linux-64", "osx-64"]
requires-pixi = ">=0.63.2"

[dependencies]
python = ">=3.13.0,<3.14"
pip = ">=24.3.1,<25"
jupyter_core = ">=5.7.2,<6"
jupyterhub-singleuser = ">=5.2.1,<6"
jupyterlab = ">=4.3.3,<5"
notebook = ">=7.3.1,<8"
nbclassic = ">=1.1.0,<2"

[feature.base-r.dependencies]
r-base = ">=4.6,<5"

[feature.essentials.dependencies]
# for pythonwhat, not on conda
asttokens = "<3"

[feature.essentials.pypi-dependencies]
pythonwhat = ">=2.3.0,<3"

[feature.r.dependencies]

[feature.datascience.dependencies]
gensim = ">=4.4.0,<5"
ipywidgets = ">=8.1.5,<9"
matplotlib = ">=3.9.4,<4"
nltk = ">=3.9.1,<4"
openpyxl = ">=3.1.5,<4"
pandas = ">=2.2.3,<3"
plotly = ">=5.24.1,<6"
scikit-learn = ">=1.6.0,<2"
scipy = ">=1.14.1,<2"
seaborn = ">=0.13.2,<0.14"
statsmodels = ">=0.14.4,<0.15"

[environments.base-r-notebook]
features = ["base-r"]
solve-group = "main"

[environments.essentials-notebook]
features = ["base-r", "essentials"]
solve-group = "main"

[environments.r-notebook]
features = ["base-r", "essentials", "r"]
solve-group = "main"

[environments.datascience-notebook]
features = ["base-r", "essentials", "r", "datascience"]
solve-group = "main"
