[project]
name = "coursekata-r-packages"
description = "R package dependencies for CourseKata Jupyter environments"

[dependencies]
IRkernel = "*"
rlang = "*"

[feature.essentials.dependencies]
coursekata = { github = "coursekata/coursekata-r", commit = "5e68e7716b02065823d17491de4a18e57774185e", force = true }  # 0.20.0
fivethirtyeight = "*"
fivethirtyeightdata = { github = "coursekata/fivethirtyeightdata", commit = "8de5de424ee5d5891fca08d4ef8734e28ff0618d" }  # master
ggpubr = "*"
gridExtra = "*"
lme4 = "*"
Lock5withR = { github = "coursekata/Lock5withR", commit = "f2773d9f828b72882ed1c4d6b3b2e539a3b3b24a" }  # master
plotly = "*"
statmod = "*"

[feature.exercises.dependencies]
testwhat = { github = "coursekata/testwhat", commit = "56502e3291c11a31301b15d63e227b4918d5d634" }  # v4.11.3.2

[feature.r.dependencies]
bayesplot = "*"
BrailleR = { github = "ajrgodfrey/BrailleR", commit = "98f0185cc8d240391a1e8c818022e68eb1d4e3c4" }  # master
car = "*"
dagitty = "*"
DHARMa = "*"
easystats = "*"
emmeans = "*"
ggdag = "*"
ggeffects = "*"
gt = "*"
here = "*"
janitor = "*"
lmerTest = "*"
loo = "*"
marginaleffects = "*"
neuralnet = "*"
posterior = "*"
psych = "*"
reticulate = "*"
sjPlot = "*"
Stat2Data = "*"
tidymodels = "*"
tidyverse = "*"

[feature.datascience.dependencies]
brms = "*"
distributions3 = "*"
nimble = "*"
rstanarm = "*"
simDAG = "*"

[feature.instructor-9e09470c-489b-4f9b-af4c-ffc524e10637.dependencies]
BH = "*"
BiocManager = "*"
"broom.mixed" = "*"
conformalbayes = "*"
cpp11 = "*"
DataExplorer = "*"
datasauRus = "*"
dqrng = "*"
extraDistr = "*"
flextable = "*"
gitcreds = "*"
latex2exp = "*"
mlpwr = "*"
mlr3verse = "*"
modelsummary = "*"
probably = "*"
progress = "*"
R4HCR = "*"
RcppArmadillo = "*"
RcppEigen = "*"
RcppProgress = "*"
renv = "*"
Rtsne = "*"
sessioninfo = "*"
sitmo = "*"
skimr = "*"
transport = "*"
truncnorm = "*"
uwot = "*"

[environments.base-r-notebook]
features = []

[environments.essentials-notebook]
features = ["essentials"]

[environments.r-notebook]
features = ["essentials", "r"]

[environments.datascience-notebook]
features = ["essentials", "r", "datascience", "instructor-9e09470c-489b-4f9b-af4c-ffc524e10637"]

[environments.datascience-core]
features = ["essentials", "r", "datascience", "instructor-9e09470c-489b-4f9b-af4c-ffc524e10637"]

[environments.exercises-notebook]
features = ["essentials", "exercises"]
