[project]
name = "coursekata-r-packages"
description = "R package dependencies for CourseKata Jupyter environments"

[dependencies]
IRkernel = "*"
rlang = "*"

[feature.essentials.dependencies]
coursekata = { github = "coursekata/coursekata-r", tag = "0.20.0", force = true }
fivethirtyeight = "*"
fivethirtyeightdata = { github = "coursekata/fivethirtyeightdata" }
ggpubr = "*"
gridExtra = "*"
lme4 = "*"
Lock5withR = { github = "coursekata/Lock5withR" }
plotly = "*"
statmod = "*"
testwhat = { github = "coursekata/testwhat", tag = "v4.11.3.2" }

[feature.r.dependencies]
bayesplot = "*"
BrailleR = { github = "ajrgodfrey/BrailleR" }
car = "*"
dagitty = "*"
DHARMa = "*"
easystats = "*"
emmeans = "*"
ggdag = "*"
ggeffects = "*"
gt = "*"
here = "*"
janitor = "*"
lmerTest = "*"
loo = "*"
marginaleffects = "*"
neuralnet = "*"
posterior = "*"
psych = "*"
reticulate = "*"
sjPlot = "*"
Stat2Data = "*"
tidymodels = "*"
tidyverse = "*"

[feature.datascience.dependencies]
brms = "*"
distributions3 = "*"
nimble = "*"
rstanarm = "*"
simDAG = "*"

[feature.instructor-9e09470c-489b-4f9b-af4c-ffc524e10637.dependencies]
BH = "*"
BiocManager = "*"
"broom.mixed" = "*"
conformalbayes = "*"
cpp11 = "*"
DataExplorer = "*"
datasauRus = "*"
dqrng = "*"
extraDistr = "*"
flextable = "*"
gitcreds = "*"
latex2exp = "*"
mlpwr = "*"
mlr3verse = "*"
modelsummary = "*"
probably = "*"
progress = "*"
R4HCR = "*"
RcppArmadillo = "*"
RcppEigen = "*"
RcppProgress = "*"
renv = "*"
Rtsne = "*"
sessioninfo = "*"
sitmo = "*"
skimr = "*"
transport = "*"
truncnorm = "*"
uwot = "*"

[environments.base-r-notebook]
features = []

[environments.essentials-notebook]
features = ["essentials"]

[environments.r-notebook]
features = ["essentials", "r"]

[environments.datascience-notebook]
features = ["essentials", "r", "datascience", "instructor-9e09470c-489b-4f9b-af4c-ffc524e10637"]
