name: datascience-notebook
channels:
  - defaults
  - conda-forge
dependencies:
  # essentials-notebook
  - pip
  - r-coursekata
  - r-fivethirtyeight
  - r-ggpubr
  - r-gridextra
  - r-lme4
  - r-plotly
  - r-statmod
  ## for r-testwhat, not on conda
  - r-evaluate
  - r-magrittr
  - r-markdown
  - r-praise
  - r-r6
  - r-stringdist
  - r-xfun

  # r-notebook
  - ocl-icd-system
  - r-av
  - r-bayesplot
  - r-broom.mixed
  - r-car
  - r-dagitty
  - r-datapasta
  - r-devtools
  - r-dharma
  - r-easystats
  - r-emmeans
  - r-fs
  - r-gganimate
  - r-ggdag
  - r-ggeffects
  - r-gifski
  - r-gt
  - r-gtsummary
  - r-here
  - r-janitor
  - r-kknn
  - r-lmertest
  - r-loo
  - r-mapdata
  - r-mapproj
  - r-marginaleffects
  - r-modelsummary
  - r-neuralnet
  - r-posterior
  - r-profvis
  - r-psych
  - r-purrr
  - r-rcpptoml
  - r-readxl
  - r-reticulate
  - r-tidybayes
  - r-tidymodels
  - r-tidyverse
  ## for r-mobilizr, not on conda
  - r-wordcloud
  - r-rpart.plot
  - r-log4r
  - r-xml
  ## for r-ocsdata, not on conda
  - r-credentials
  - r-gert
  - r-gh
  - r-gitcreds
  - r-httr2
  - r-ini
  - r-zip
  - r-usethis
  - r-whisker
  # for r-simstudy, not on conda
  - r-bh
  - r-bigmemory
  - r-bigmemory.sri
  - r-fastglm
  - r-mvnfast
  # "r-pbv

  # datascience-notebook
  - ipywidgets=8.*
  - matplotlib=3.*
  - nltk=3.*
  - numpy=1.*
  - openpyxl=3.*
  - pandas=2.*
  - plotly=5.*
  - scikit-learn=1.*
  - seaborn=0.11.*
  - statsmodels=0.14.*
  # instructor-requested packages
  - altair=4.*
  - beautifulsoup4=4.*
  - bokeh=3.*
  - cmdstanpy=1.*
  - contextily=1.*
  - dash=2.*
  - folium=0.14.*
  - gensim=4.*
  - geopandas=0.12.*
  - dtreeviz=2.*
  - mapclassify=2.*
  - networkx=3.*
  - researchpy=0.*
  - scipy=1.*
  - spotipy=2.*
  - vega_datasets=0.9.*
  - wordcloud=1.*
  - yellowbrick=1.*
  - cmdstan
  - r-brms
  - r-cmdstanr
  - r-ggstatsplot
  - r-rstanarm
  ## for r-rethinking, not on conda
  - r-coda
  - r-digest

  - pip:
      - pythonwhat @ git+https://github.com/coursekata/pythonwhat@master

      # datascience-notebook, instructor-requested packages
      - altair-latimes
      - dash-cytoscape
      - yahoo-fin
