---
name: Docker Image Publisher
description: Build, test, and publish a Docker image.
inputs:
  image:
    description: "The name of the image to build"
    required: true
  labels:
    description: "Labels to add to the image"
    required: false
    default: ""
  tags:
    description: "Tags to add to the image"
    required: false
    default: ""
  platforms:
    description: "Platforms to build for"
    required: false
    default: |
      linux/amd64
      linux/arm64/v8
  build-args:
    description: "Extra build arguments to pass to the image"
    required: false
    default: ""
  push:
    description: "Whether to push the image to the registry"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    # https://github.com/docker/metadata-action
    - name: Image Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ github.repository_owner }}/${{ inputs.image }}
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern={{date 'YYYY-MM-DD'}}
          type=sha
          ${{ inputs.tags }}
        labels: |
          org.opencontainers.image.title=${{ inputs.image }}
          org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/docker-stacks/pkgs/container/${{ inputs.image }}
          ${{ inputs.labels }}

    # https://github.com/docker/build-push-action
    - name: Build for current platform and load into Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        context: ${{ inputs.image }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ github.repository_owner }}/${{ inputs.image }}:test

    - name: Test
      shell: bash
      run: |
        docker run --rm --mount=type=bind,source="./tests/${{ inputs.image }}.sh",target=/tmp/test.sh \
        ${{ github.repository_owner }}/${{ inputs.image }}:test bash /tmp/test.sh

    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push == true }}
        context: ${{ inputs.image }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
