#!/usr/bin/env Rscript

# R packages for the datascience-notebook image.
#
# GENERATED by scripts/rpak.R from rpixi.toml — do not edit by hand.
# Regenerate with: Rscript scripts/rpak.R pakgen
#
# Self-contained on purpose: the only thing this needs is pak, so the image
# does not have to ship a TOML parser or any conda r-* package.

options(warn = 2)  # a failed install must fail the build, not warn

if (!requireNamespace("pak", quietly = TRUE)) {
  # From the one repository Rprofile.site configures. pak resolves everything
  # else in this image, so it must not come from somewhere else: a fallback
  # repo here reintroduces the ambiguity Rprofile.site exists to remove.
  install.packages("pak")
}

options(
  pkg.sysreqs = TRUE,
  pkg.sysreqs_platform = "ubuntu-24.04"
)

message("Installing 69 R packages for datascience-notebook ...")
pak::pkg_install(
  c(
    "IRkernel",
    "rlang",
    "coursekata/Lock5withR",
    "coursekata/coursekata-r@0.20.0?reinstall",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2",
    "ajrgodfrey/BrailleR",
    "DHARMa",
    "Stat2Data",
    "bayesplot",
    "car",
    "dagitty",
    "easystats",
    "emmeans",
    "ggdag",
    "ggeffects",
    "gt",
    "here",
    "janitor",
    "lmerTest",
    "loo",
    "marginaleffects",
    "neuralnet",
    "posterior",
    "psych",
    "reticulate",
    "sjPlot",
    "tidymodels",
    "tidyverse",
    "brms",
    "distributions3",
    "nimble",
    "rstanarm",
    "simDAG",
    "BH",
    "BiocManager",
    "DataExplorer",
    "R4HCR",
    "RcppArmadillo",
    "RcppEigen",
    "RcppProgress",
    "Rtsne",
    "broom.mixed",
    "conformalbayes",
    "cpp11",
    "datasauRus",
    "dqrng",
    "extraDistr",
    "flextable",
    "gitcreds",
    "latex2exp",
    "mlpwr",
    "mlr3verse",
    "modelsummary",
    "probably",
    "progress",
    "renv",
    "sessioninfo",
    "sitmo",
    "skimr",
    "transport",
    "truncnorm",
    "uwot"
  ),
  upgrade = FALSE,
  ask = FALSE
)

message("R package installation complete.")

