#!/usr/bin/env Rscript

# R packages for the datascience-notebook image.
#
# GENERATED by scripts/rpak.R from rpixi.toml — do not edit by hand.
# Regenerate with: Rscript scripts/rpak.R pakgen
#
# Self-contained on purpose: the only thing this needs is pak, so the image
# does not have to ship a TOML parser or any conda r-* package.

options(warn = 2)  # a failed install must fail the build, not warn

if (!requireNamespace("pak", quietly = TRUE)) {
  # Prefer the prebuilt binary; fall back to CRAN source.
  ok <- tryCatch({
    install.packages("pak", repos = sprintf(
      "https://r-lib.github.io/p/pak/stable/%s/%s/%s",
      .Platform$pkgType, R.Version()$os, R.Version()$arch))
    requireNamespace("pak", quietly = TRUE)
  }, error = function(e) FALSE)
  if (!ok) install.packages("pak", repos = "https://cloud.r-project.org")
}

options(
  pkg.sysreqs = TRUE,
  pkg.sysreqs_platform = "ubuntu-24.04"
)

# Custom repositories must be configured BEFORE resolution, not after.
# Packages outside CRAN (cmdstanr) and packages that depend on them
# (rethinking) are resolved in the same pass, so a repo added afterwards
# is too late and the whole solve fails.
options(repos = c(getOption("repos"), "https://mc-stan.org/r-packages/"))

message("Installing 57 R packages for datascience-notebook ...")
pak::pkg_install(
  c(
    "IRkernel",
    "rlang",
    "coursekata/Lock5withR",
    "coursekata/coursekata-r?reinstall",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2",
    "DHARMa",
    "OCSdata",
    "RcppTOML",
    "Stat2Data",
    "V8?reinstall",
    "av",
    "bayesplot",
    "broom.mixed",
    "car",
    "dagitty",
    "datapasta",
    "easystats",
    "emmeans",
    "gganimate",
    "ggdag",
    "ggeffects",
    "gifski",
    "gt",
    "gtsummary",
    "here",
    "janitor",
    "lmerTest",
    "loo",
    "mapdata",
    "mapproj",
    "marginaleffects",
    "mobilizingcs/mobilizr",
    "neuralnet",
    "posterior",
    "profvis",
    "psych",
    "reticulate",
    "simstudy",
    "sjPlot",
    "tidybayes",
    "tidymodels",
    "tidyverse",
    "brms",
    "cmdstanr",
    "distributions3",
    "ggstatsplot",
    "nimble",
    "rmcelreath/rethinking@v2.2.1",
    "rstanarm",
    "simDAG"
  ),
  upgrade = FALSE,
  ask = FALSE
)

message("R package installation complete.")

