#!/usr/bin/env Rscript

#' CourseKata R Package Installer
#'
#' This script installs R packages for the datascience-notebook environment
#' using the pak package manager.
#'
#' Generated by rpixi pakgen v1.0.0
#' Environment: datascience-notebook
#' Package count: 56
#' Source: ./rpixi.toml
#'
#' Usage:
#'   Rscript datascience-notebook.R
#'   # or
#'   ./datascience-notebook.R

# Bootstrap pak package manager
if (!requireNamespace("pak", quietly = TRUE)) {
  message("Installing pak...")
  install.packages("pak", repos = "https://cloud.r-project.org/")
}

# Install packages (55 total)
message("Installing 55 packages...")
pak::pkg_install(
  c(
    # Base dependencies
    "IRkernel",
    "rlang",

    # Feature: essentials
    "coursekata/Lock5withR",
    "coursekata",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2",

    # Feature: r
    "DHARMa",
    "OCSdata",
    "RcppTOML",
    "Stat2Data",
    "V8",
    "av",
    "bayesplot",
    "broom.mixed",
    "car",
    "dagitty",
    "datapasta",
    "easystats",
    "emmeans",
    "gganimate",
    "ggdag",
    "ggeffects",
    "gifski",
    "gt",
    "gtsummary",
    "here",
    "janitor",
    "lmerTest",
    "loo",
    "mapdata",
    "mapproj",
    "marginaleffects",
    "mobilizingcs/mobilizr",
    "neuralnet",
    "posterior",
    "profvis",
    "psych",
    "reticulate",
    "simstudy",
    "sjPlot",
    "tidybayes",
    "tidymodels",
    "tidyverse",

    # Feature: datascience
    "brms",
    "ggstatsplot",
    "nimble",
    "rmcelreath/rethinking@v2.2.1",
    "rstanarm",
    "simDAG"
  ),
  upgrade = FALSE
)

# Custom repo: cmdstanr from https://mc-stan.org/r-packages/
message("Installing cmdstanr from custom repository...")
options(repos = c(getOption("repos"), "https://mc-stan.org/r-packages/"))
pak::pkg_install("cmdstanr", upgrade = FALSE)

message("Installation complete!")
