#!/usr/bin/env Rscript

#' CourseKata R Package Installer
#'
#' This script installs R packages for the default environment
#' using the pak package manager.
#'
#' Generated by rpixi pakgen v1.0.0
#' Environment: default
#' Package count: 2
#' Source: ./rpixi.toml
#'
#' Usage:
#'   Rscript default.R
#'   # or
#'   ./default.R

# Bootstrap pak package manager
if (!requireNamespace("pak", quietly = TRUE)) {
  message("Installing pak...")
  install.packages("pak", repos = "https://cloud.r-project.org/")
}

# Install packages (2 total)
message("Installing 2 packages...")
pak::pkg_install(
  c(
    # Base dependencies
    "IRkernel",
    "rlang"
  ),
  upgrade = FALSE
)

message("Installation complete!")
