#!/usr/bin/env Rscript

#' CourseKata R Package Installer
#'
#' This script installs R packages for the essentials-notebook environment
#' using the pak package manager.
#'
#' Generated by rpixi pakgen v1.0.0
#' Environment: essentials-notebook
#' Package count: 12
#' Source: ./rpixi.toml
#'
#' Usage:
#'   Rscript essentials-notebook.R
#'   # or
#'   ./essentials-notebook.R

# Bootstrap pak package manager
if (!requireNamespace("pak", quietly = TRUE)) {
  message("Installing pak...")
  install.packages("pak", repos = "https://cloud.r-project.org/")
}

# Install packages (12 total)
message("Installing 12 packages...")
pak::pkg_install(
  c(
    # Base dependencies
    "IRkernel",
    "rlang",

    # Feature: essentials
    "coursekata/Lock5withR",
    "coursekata",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2"
  ),
  upgrade = FALSE
)

message("Installation complete!")
