#!/usr/bin/env Rscript

# R packages for the essentials-notebook image.
#
# GENERATED by scripts/rpak.R from rpixi.toml — do not edit by hand.
# Regenerate with: Rscript scripts/rpak.R pakgen
#
# Self-contained on purpose: the only thing this needs is pak, so the image
# does not have to ship a TOML parser or any conda r-* package.

options(warn = 2)  # a failed install must fail the build, not warn

if (!requireNamespace("pak", quietly = TRUE)) {
  # From the one repository Rprofile.site configures. pak resolves everything
  # else in this image, so it must not come from somewhere else: a fallback
  # repo here reintroduces the ambiguity Rprofile.site exists to remove.
  install.packages("pak")
}

options(
  pkg.sysreqs = TRUE,
  pkg.sysreqs_platform = "ubuntu-24.04"
)

message("Installing 12 R packages for essentials-notebook ...")
pak::pkg_install(
  c(
    "IRkernel",
    "rlang",
    "coursekata/Lock5withR",
    "coursekata/coursekata-r@0.20.0?reinstall",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2"
  ),
  upgrade = FALSE,
  ask = FALSE
)

message("R package installation complete.")

