#!/usr/bin/env Rscript

#' CourseKata R Package Installer
#'
#' This script installs R packages for the r-notebook environment
#' using the pak package manager.
#'
#' Generated by rpixi pakgen v1.0.0
#' Environment: r-notebook
#' Package count: 49
#' Source: ./rpixi.toml
#'
#' Usage:
#'   Rscript r-notebook.R
#'   # or
#'   ./r-notebook.R

# Bootstrap pak package manager
if (!requireNamespace("pak", quietly = TRUE)) {
  message("Installing pak...")
  install.packages("pak", repos = "https://cloud.r-project.org/")
}

# Install packages (49 total)
message("Installing 49 packages...")
pak::pkg_install(
  c(
    # Base dependencies
    "IRkernel",
    "rlang",

    # Feature: essentials
    "coursekata/Lock5withR",
    "coursekata",
    "fivethirtyeight",
    "coursekata/fivethirtyeightdata",
    "ggpubr",
    "gridExtra",
    "lme4",
    "plotly",
    "statmod",
    "coursekata/testwhat@v4.11.3.2",

    # Feature: r
    "DHARMa",
    "OCSdata",
    "RcppTOML",
    "Stat2Data",
    "V8",
    "av",
    "bayesplot",
    "broom.mixed",
    "car",
    "dagitty",
    "datapasta",
    "easystats",
    "emmeans",
    "gganimate",
    "ggdag",
    "ggeffects",
    "gifski",
    "gt",
    "gtsummary",
    "here",
    "janitor",
    "lmerTest",
    "loo",
    "mapdata",
    "mapproj",
    "marginaleffects",
    "mobilizingcs/mobilizr",
    "neuralnet",
    "posterior",
    "profvis",
    "psych",
    "reticulate",
    "simstudy",
    "sjPlot",
    "tidybayes",
    "tidymodels",
    "tidyverse"
  ),
  upgrade = FALSE
)

message("Installation complete!")
