name: Setup Docker
description: Install Docker Buildx with QEMU and login to GHCR.
inputs:
  github-token:
    description: The token from `secrets.GITHUB_TOKEN`.
    required: true
runs:
  using: "composite"
  steps:
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
