name: Build and push
description: Build a docker image and push it to a repository.

inputs:
  context:
    required: true
    description: The directory to use for the build context (also used as image name).
  python-version:
    required: false
    description: The Python version installed on the image.
  r-version:
    required: false
    description: The R version installed on the image.
  base-tag:
    required: false
    description: The tag for the image to build from.

runs:
  using: "composite"
  steps:
    # https://github.com/docker/metadata-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/coursekata/${{ inputs.build-context }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern={{date 'YYYY-MM-DD'}}
          type=sha
          type=raw,value=r-${{ inputs.r-version }}
          type=raw,value=python-${{ inputs.python-version }}

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ${{ inputs.build-context }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build_args:
          PYTHON_VERSION: ${{ inputs.python-version }}
          R_VERSION: ${{ inputs.r-version }}
          BASE_TAG: ${{ inputs.base-tag }}
