name: Setup Docker
description: Install Docker Buildx with QEMU and login to GHCR.

inputs:
  github-token:
    description: The token from `secrets.GITHUB_TOKEN`.
    required: true
  extra-tags:
    description: Extra docker/metadata-action tag specifications to append.
    required: false
    default: ""
  build-args:
    description: Build arguments passed to docker/build-push-action.
    required: false
    default: ""
  build-contexts:
    description: Build contexts passed to docker/build-push-action.
    required: false
    default: ""
  cache-from:
    description: Build cache-from passed to docker/build-push-action.
    required: false
    default: type=gha
  cache-to:
    description: Build cache-to passed to docker/build-push-action.
    required: false
    default: type=gha

runs:
  using: "composite"
  steps:
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    # https://github.com/docker/metadata-action
    - name: Image Metdata
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/coursekata/${{ github.job }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern={{date 'YYYY-MM-DD'}}
          type=sha
          ${{ inputs.extra-tags }}

    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ${{ github.job }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        platforms: ${{ env.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-contexts: scripts=scripts
        build-args: ${{ inputs.build-args }}
