---
name: Bake Images

on:
  workflow_dispatch:
  push:
    branches: [feature/*]
    paths:
      - .github/workflows/publish2.yml
      - docker-bake.hcl
      - pixi.lock
      - pixi.toml
      - packages.yaml
      - dockerfiles/**
      - scripts/**
      - assets/**
  schedule:
    # Weekly, at 03:00 on Monday UTC time (see https://crontab.guru)
    - cron: "0 3 * * 1"

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      target: base
