---
name: Test images

on:
  workflow_dispatch:
  push:
    branches: [test/*]
    paths:
      - .github/workflows/test.yml
      - .github/actions/build-test-push/**
      - tests/**
      - base-r-notebook/**
      - essentials-notebook/**
      - r-notebook/**
      - datascience-notebook/**

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  base-image: jupyter/minimal-notebook
  python-version: "3.11"
  r-version: "4.3"
  tags: |
    type=raw,value=python-3.11
    type=raw,value=r-4.3

jobs:
  docker:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      # https://github.com/jlumbroso/free-disk-space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false

      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # network=host driver-opt needed to push to local registry
          driver-opts: network=host

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: base-r build and test
        id: base-r
        uses: ./.github/actions/build-test-push
        with:
          image: base-r-notebook
          tags: ${{ env.tags }}
          labels: |
            org.opencontainers.image.title=Base R Notebook
            org.opencontainers.image.description=Jupyter Lab, Python, and R, and that's it.
          build-args: |
            PYTHON_VERSION=${{ env.python-version }}
            R_VERSION=${{ env.r-version }}

      - name: essentials build and test
        id: essentials
        uses: ./.github/actions/build-test-push
        with:
          image: essentials-notebook
          tags: ${{ env.tags }}
          labels: |
            org.opencontainers.image.title=Essentials Notebook
            org.opencontainers.image.description=CourseKata essentials: everything used in the books.
          build-args: |
            BASE_IMAGE=${{ steps.base-r.outputs.image }}
            PARENT_IMAGE=${{ steps.base-r.outputs.image }}

      - name: r build and test
        id: r
        uses: ./.github/actions/build-test-push
        with:
          image: r-notebook
          tags: ${{ env.tags }}
          labels: |
            org.opencontainers.image.title=R Notebook
            org.opencontainers.image.description=CourseKata essentials and other R packages for teaching and learning data science.
          build-args: |
            BASE_IMAGE=${{ steps.base-r.outputs.image }}
            PARENT_IMAGE=${{ steps.essentials.outputs.image }}

      - name: datascience build and test
        uses: ./.github/actions/build-test-push
        with:
          image: datascience-notebook
          tags: ${{ env.tags }}
          labels: |
            org.opencontainers.image.title=Data Science Notebook
            org.opencontainers.image.description=R and Python packages for teaching and learning data science.
          build-args: |
            BASE_IMAGE=${{ steps.base-r.outputs.image }}
            PARENT_IMAGE=${{ steps.r.outputs.image }}
