---
name: Test images

on:
  workflow_dispatch:
  push:
    branches: [test/*]
    paths:
      - .github/workflows/test.yml
      - .github/workflows/build-test-publish.yml
      - .github/workflows/build-test-publish-all.yml
      - tests/**
      - base-r-notebook/**
      - essentials-notebook/**
      - r-notebook/**
      - datascience-notebook/**

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/build-test-publish-all.yml
    secrets: inherit
    with:
      publish: false
