---
name: Make Test Baked Images

on:
  workflow_dispatch:
  push:
    branches:
      - test
      - test/*
      - feature/*
      - hotfix/*
    paths:
      - .github/workflows/publish2.yml
      - .github/workflows/bake.yml
      - docker-bake.hcl
      - pixi.lock
      - pixi.toml
      - packages.yaml
      - dockerfiles/**
      - scripts/**
      - assets/**
  schedule:
    # Weekly, at 03:00 on Monday UTC time (see https://crontab.guru)
    - cron: "0 3 * * 1"

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      target: base

  images:
    needs: [base]
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      target: ${{ matrix.target }}
      free-disk-space: true
      registry: ghcr.io/coursekata/test
    strategy:
      fail-fast: false
      matrix:
        target:
          - base-r
          - ckcode
          - deepnote-ckcode-r
